project:
  type: book

book:
  title: "PHS 650: Final Project"
  author: "Aly, Haley, Zoe"
  date: "4/26/2023"
  chapters:
    - index.qmd
    - methods.qmd
    - results.qmd
    - references.qmd


bibliography: references.bib

format:
  html:
    title-block-banner: true
    author: "Aly, Haley, Zoe"
    date: "4/26/2023"
    description: "An analysis of duration and intensity of songs as predictors of song popularity"
    toc: false
  pdf:
    title-block-banner: false
    documentclass: scrreprt

editor: visual

