project:
  type: book
  output-dir: docs
  
book:
  title: "PHS 650: Final Project"
  author: "Aly, Haley, Zoe"
  date: "4/26/2023"
  chapters:
    - index.qmd
    - methods.qmd
    - results.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    title-block-banner: true
    description: "An analysis of duration and intensity of songs as predictors of song popularity"
    author: "Aly, Haley, Zoe"
    date: "2023-04-26"
    date-format: short
    toc: false
  pdf:
    documentclass: scrreprt
  docx:
    toc: true
    toc-title: Contents
    number-sections: true
    highlight-style: github
    description: "An analysis of duration and intensity of songs as predictors of song popularity"
    
editor: visual

