# Introduction {.unnumbered}

In the music industry, there is a consideration of what song will be popular or a 'hit,' as song popularity is associated with more revenue [@phamPredictingSongPopularity2015]. Thus, predicting the popularity of a song, referred to as the Hit Song Science, can be useful in determining which songs should receive the most investment from musicians and their labels. Random forests have been found to accurately predict which songs will be popular and determined that songs that 'made it' to the top charts were found to be 'happier' and more 'party-like' [@interianoMusicalTrendsPredictability2018; @middlebrookSongHitPrediction2019]. Additionally, artist familiarity, loudness, year of release, and number of genres were also found to accurately predict the popularity of songs [@phamPredictingSongPopularity2015]. In Billboard Top 100 and the Spotify Global Top 50 songs, the length of songs has been decreasing since the 90's, while changes in energy and danceability, although tending to increase, have been inconsistent. [@vanderheideOldTownRoad2019]

The goal of our project is to contribute to the field of Hit Song Science and examine how song elements, specifically the duration and intensity, are associated with a song's popularity. We hypothesize that shorter songs are more likely to be popular. We also hypothesize that more intense songs are more likely to be popular.
